# Generated by Django 3.2.9 on 2021-11-01 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_comment_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="link",
            field=models.URLField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="upvote",
            field=models.IntegerField(default=0),
        ),
    ]
